//
//  Tutor.swift
//  Tutors
//
//  Created by Sai Kambampati on 6/5/19.
//  Copyright © 2019 AppCoda. All rights reserved.
//

import SwiftUI

struct Tutor: Identifiable {
    var id = UUID()
    var name: String
    var headline: String
    var top1: String
    var top2: String
    var top3: String
    var top4: String
    var top5: String
    var top6: String
    var top7: String
    var top8: String
    var top9: String
    var top10: String
    
    
    var imageName: String { return name }
}

#if DEBUG
let testData = [
    Tutor(name: "Alabama", headline: "Top 10 SDoH Percentile Ranking",
          top1: "Medicare Fee-for-Service Beneficiaries Diagnosed with High Blood Pressure",
          top2:"Medicare Fee-for-Service Beneficiaries Diagnosed with diabetes",
          top3:"Medicare Fee-for-Service Beneficiaries Diagnosed with Chronic Kidney Disease",
          top4:"Percent of non-federal jobs in Utilities in 2019",
          top5:"Medicare Fee-for-Service Beneficiaries Diagnosed with Heart Failure",
          top6:"Percent of non-federal jobs in Manufacturing in 2019",
          top7:"Population Black or African American (Alone)",
          top8:"Population Black or African American (Alone) Non-Hispanic/Latino",
          top9: "Adults Ever Diagnosed with Depression",
          top10:"Percent of Adults Reporting to be Obese (BMI of 30 or Greater)"),
    Tutor(name: "Alaska", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Estimated Average Annual Amount Spent per Household on Housing",
          top2:"Percent Change in the Number of Deaths from Coronary Heart Disease",
          top3:"Estimated Average Annual Amount Spent per Household on Food Away from Home",
          top4:"Amount Spent per Household on All Household Expenses",
          top5:"Percent Change in the Number of Deaths from Stroke",
          top6:"Amount Spent per Household on Alcohol",
          top7:"Percent Population Asian (Alone)",
          top8:"Percent Population Asian (Alone) Non-Hispanic/Latino",
          top9:"Estimated Median Income of a Household",
          top10:"Percent of Total Expenses Spent on Education : 0.784"),
    Tutor(name: "Arizona", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent Population  Hispanic or Latino",
          top2:"Percent Change in the Number of Deaths from Coronary Heart Disease",
          top3:"Percent Change in the Number of Deaths from Chronic Lower Respiratory Disease",
          top4:"Percent of non-federal jobs in Utilities in 2019",
          top5:"Percent of non-federal jobs in Mining, Quarrying, and Oil and Gas Extraction in 2019",
          top6:"Percent of non-federal jobs in Construction in 2019",
          top7:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with High Cholesterol",
          top8:"Percent Families in Poverty",
          top9:"Percent Change in the Number of Deaths from Stroke",
          top10:"Percent Population Asian (Alone)"),
    Tutor(name: "Arkansas", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Adults Reporting to be Obese (BMI of 30 or Greater)",
          top2:"Percent Change in the Number of Deaths from Chronic Lower Respiratory Disease",
          top3:"Percent of Total Expenses Spent on Housing",
          top4:"Percent of Adults Reporting to be Overweight (BMI > 24.9)",
          top5:"Percent of Adults Ever Diagnosed with Diabetes",
          top6:"Percent of Medicare Medicare Fee-for-Service Beneficiaries Diagnosed with Coronary Artery Disease",
          top7:"Rate of Adult Deaths from Cancer per 100,000 People",
          top8:"Percent of non-federal jobs in Manufacturing in 2019",
          top9:"Percent Families in Poverty",
          top10:"Percent of non-federal jobs in Utilities in 2019"),
    Tutor(name: "California", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent Population Asian (Alone)",
          top2:"Percent Population Asian (Alone) Non-Hispanic/Latino",
          top3:"Percent Population  Hispanic or Latino",
          top4:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019",
          top5:"Estimated Median Income of a Household",
          top6:"Percent of Adults Reporting to be Overweight (BMI > 24.9 and < 30)",
          top7:"Percent of Total Expenses Spent on Education",
          top8:"Estimated Average Annual Amount Spent per Household on Food Away from Home",
          top9:"Estimated Average Annual Amount Spent per Household on Housing",
          top10:"Amount Spent per Household on All Household Expenses"),
    Tutor(name: "Colorado", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Population with at least a Bachelor's Degree",
          top2:"Rate of Beer, Wine, and Liquor Stores per 100,000 People",
          top3:"Estimated Median Income of a Family",
          top4:"Percent Population  Hispanic or Latino",
          top5:"Percent of non-federal jobs in Construction in 2019",
          top6:"Rate of Fitness and Recreational Sports Centers per 100,000 People",
          top7:"Percent of non-federal jobs in Mining, Quarrying, and Oil and Gas Extraction in 2019",
          top8:"Amount Spent per Household on Alcohol",
          top9:"Estimated Average Annual Amount Spent per Household on Housing",
          top10:"Estimated Median Income of a Household"),
    Tutor(name: "Connecticut", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Adults Reporting to be Overweight (BMI > 24.9 and < 30)",
          top2:"Rate of Beer, Wine, and Liquor Stores per 100,000 People",
          top3:"Amount Spent per Household on Alcohol",
          top4:"Percent of Adults Reporting a Physical Checkup in the Past Year",
          top5:"Estimated Average Annual Amount Spent per Household on Food Away from Home",
          top6:"Estimated Average Annual Amount Spent per Household on Housing",
          top7:"Estimated Median Income of a Family",
          top8:"Amount Spent per Household on All Household Expenses",
          top9:"Rate of Fitness and Recreational Sports Centers per 100,000 People",
          top10:"Estimated Median Income of a Household"),
    Tutor(name: "Delaware", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with High Cholesterol",
          top2:"Rate of Beer, Wine, and Liquor Stores per 100,000 People",
          top3:"Percent of Medicare Medicare Fee-for-Service Beneficiaries Diagnosed with High Blood Pressure",
          top4:"Rate of Fitness and Recreational Sports Centers per 100,000 People",
          top5:"Average Annual Dollars per Person Spent on Medical Care",
          top6:"Percent Change in the Number of Deaths from Stroke",
          top7:"Percent Population Black or African American (Alone)",
          top8:"Percent Population Black or African American (Alone) Non-Hispanic/Latino",
          top9:"Percent of Adults Reporting a Physical Checkup in the Past Year",
          top10:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with Diabetes"),
    Tutor(name: "District of Columbia", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Amount Spent per Household on Alcohol",
          top2:"Estimated Median Income of a Family",
          top3:"Estimated Median Income of a Household",
          top4:"Percent of Population with at least a Bachelor's Degree",
          top5:"Percent Population Black or African American (Alone)",
          top6:"Percent Population Black or African American (Alone) Non-Hispanic/Latino",
          top7:"Rate of Limited-Service Restaurants per 100,000 People",
          top8:"Rate of Fitness and Recreational Sports Centers per 100,000 People",
          top9:"Percent Population with Health Insurance",
          top10:"Rate of Beer, Wine, and Liquor Stores per 100,000 People"),
    Tutor(name: "Florida", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with Coronary Artery Disease",
          top2:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with High Cholesterol",
          top3:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with Chronic Kidney Disease",
          top4:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with High Blood Pressure",
          top5:"Percent Population  Hispanic or Latino",
          top6:"Percent of Adults Reporting a Physical Checkup in the Past Year",
          top7:"Percent Change in the Number of Deaths from Stroke",
          top8:"Percent of Adults Ever Diagnosed with Diabetes",
          top9:"Average Annual Dollars per Person Spent on Medical Care",
          top10:"Percent Population Black or African American (Alone)"),
    Tutor(name: "Georgia", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent Population Black or African American (Alone)",
          top2:"Percent Population Black or African American (Alone) Non-Hispanic/Latino",
          top3:"Percent of non-federal jobs in Transportation and Warehousing in 2019",
          top4:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with Chronic Kidney Disease",
          top5:"Rate of Limited-Service Restaurants per 100,000 People in 2017",
          top6:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with High Blood Pressure",
          top7:"Percent Change in the Number of Deaths from Chronic Lower Respiratory Disease6",
          top8:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with High Cholesterol",
          top9:"Percent of Adults Ever Diagnosed with Diabetes",
          top10:"Percent Change in the Number of Deaths from Stroke"),
    Tutor(name: "Hawaii", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent Population Asian (Alone)",
          top2:"Percent Population Asian (Alone) Non-Hispanic/Latino",
          top3:"Percent of non-federal jobs in Transportation and Warehousing in 2019",
          top4:"Rate of Limited-Service Restaurants per 100,000 People",
          top5:"Percent Change in the Number of Deaths from Stroke",
          top6:"Percent Population with Health Insurance",
          top7:"Average Annual Dollars per Person Spent on Medical Care",
          top8:"Percent of non-federal jobs in Utilities in 2019",
          top9:"Estimated Average Annual Amount spent per Household on Food Away from Home",
          top10:"Estimated Average Annual Amount spent per Household on Housing"),
    Tutor(name: "Idaho", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019",
          top2:"Percent Population White (Alone)",
          top3:"Percent Population White (Alone) Non-Hispanic/Latino",
          top4:"Percent Change in the Number of Deaths from Stroke",
          top5:"Percent of Total Expenses Spent on Housing",
          top6:"Percent of non-federal jobs in Construction in 2019",
          top7:"Percent Change in the Number of Deaths from Chronic Lower Respiratory Disease",
          top8:"Percent of Adults Reporting to be Overweight (BMI > 24.9 and < 30)",
          top9:"Percent Change in the Number of Deaths from Coronary Heart Disease",
          top10:"Percent Population  Hispanic or Latino"),
    Tutor(name: "Illinois", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of non-federal jobs in Transportation and Warehousing in 2019",
          top2:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with Heart Failure",
          top3:"Percent Population Asian (Alone)",
          top4:"Percent Population  Hispanic or Latino",
          top5:"Percent Population Asian (Alone) Non-Hispanic/Latino",
          top6:"Rate of Limited-Service Restaurants per 100,000 People in 2017",
          top7:"Percent of Population with at least a Bachelor's Degree",
          top8:"Percent of Adults Reporting to Have a Personal Doctor or Health Care Provider",
          top9:"Percent Population Black or African American (Alone) Non-Hispanic/Latino",
          top10:"Percent Population Black or African American (Alone)"),
    Tutor(name: "Indiana", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of non-federal jobs in Manufacturing in 2019",
          top2:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with Depression",
          top3:"Percent of non-federal jobs in Transportation and Warehousing in 2019",
          top4:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with Heart Failure",
          top5:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with Chronic Kidney Disease",
          top6:"Percent Change in the Number of Deaths from Chronic Lower Respiratory Disease",
          top7:"Percent of Medicare Fee-for-Service Beneficiaries Diagnosed with Coronary Artery Disease",
          top8:"Percent of Adults Ever Diagnosed with Diabetes",
          top9:"Rate of Adult Deaths from Cancer per 100,000 People",
          top10:"Percent of Total Expenses Spent on Housing"),
    Tutor(name: "Iowa", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of non-federal jobs in Manufacturing in 2019",
          top2:"Percent Population White (Alone) Non-Hispanic/Latino",
          top3:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019",
          top4:"Percent Population White (Alone) : 0.882",
          top5:"Percent population with health insurance : 0.882",
          top6:"Percent of Adults Reporting to be Obese (BMI of 30 or Greater) : 0.88",
          top7:"Percent of Adults Reporting to be Overweight (BMI > 24.9) : 0.84",
          top8:"Average Annual Dollars per Person Spent on Medical Care : 0.784",
          top9:"Percent of Adults Reporting to Have a Personal Doctor or Health Care Provider : 0.78",
          top10:"Percent of non-federal jobs in Transportation and Warehousing in 2019 : 0.687"),
    Tutor(name: "Kansas", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Rate of beer, wine, and liquor stores per 100,000 people : 0.882",
          top2:"Percent change in the number of deaths from coronary heart disease : 0.82",
          top3:"Percent of Adults Reporting to be Overweight (BMI > 24.9) : 0.78",
          top4:"Percent of non-federal jobs in Manufacturing in 2019 : 0.77",
          top5:"Percent of Adults Reporting to be Obese (BMI of 30 or Greater) : 0.76",
          top6:"Percent of non-federal jobs in Mining, Quarrying, and Oil and Gas Extraction in 2019 : 0.75",
          top7:"Percent of population with at least a bachelor's degree : 0.666",
          top8:"Percent Population  Hispanic or Latino : 0.666",
          top9:"Percent Population White (Alone) : 0.647",
          top10:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019 : 0.645"),
    Tutor(name: "Kentucky", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Rate of adult deaths from cancer per 100,000 people in 2020. : 0.96",
          top2:"Percent of non-federal jobs in Transportation and Warehousing in 2019 : 0.958",
          top3:"Percent of Adults Reporting to be Obese (BMI of 30 or Greater) : 0.92",
          top4:"Percent Families in Poverty : 0.901",
          top5:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with high blood pressure : 0.901",
          top6:"Percent of Adults Ever Diagnosed with Depression : 0.9",
          top7:"Percent of non-federal jobs in Manufacturing in 2019 : 0.895",
          top8:"Percent of Total Expenses Spent on Housing : 0.882",
          top9:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with depression : 0.882",
          top10:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with heart failure : 0.882"),
    Tutor(name: "Louisiana", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of non-federal jobs in Construction in 2019 : 1",
          top2:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with high blood pressure : 0.98",
          top3:"Percent Families in Poverty : 0.96",
          top4:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with coronary artery disease : 0.96",
          top5:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with heart failure : 0.96",
          top6:"Percent Population Black or African American (Alone) : 0.96",
          top7:"Percent Population Black or African American (Alone) Non-Hispanic/Latino : 0.96",
          top8:"Percent of Adults Ever Diagnosed with Diabetes : 0.94",
          top9:"Percent of Adults Reporting to be Obese (BMI of 30 or Greater) : 0.94",
          top10:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with chronic kidney disease : 0.901"),
    Tutor(name: "Maine", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent Population White (Alone) Non-Hispanic/Latino : 1",
          top2:"Percent Population White (Alone) : 1",
          top3:"Average Annual Dollars per Person Spent on Medical Care : 1",
          top4:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with depression : 0.98",
          top5:"Rate of adult deaths from cancer per 100,000 people in 2020. : 0.98",
          top6:"Percent of Adults Reporting to Have a Personal Doctor or Health Care Provider : 0.92",
          top7:"Percent change in the number of deaths from stroke : 0.88",
          top8:"Percent of Adults Ever Diagnosed with Depression : 0.8",
          top9:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019 : 0.708",
          top10:"Percent of Adults Reporting to be Overweight (BMI > 24.9 and < 30) : 0.64"),
    Tutor(name: "Maryland", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Estimated average annual amount spent per household on food away from home : 1",
          top2:"Estimated average annual amount spent per household on housing : 1",
          top3:"Amount Spent per Household on All Household Expenses : 1",
          top4:"Amount Spent per Household on Alcohol : 0.98",
          top5:"Estimated median income of a household : 0.98",
          top6:"Percent of Total Expenses Spent on Education : 0.96",
          top7:"Estimated median income of a family : 0.96",
          top8:"Percent of population with at least a bachelor's degree : 0.941",
          top9:"Rate of limited-service restaurants per 100,000 people in 2017. : 0.941",
          top10:"Percent Population Black or African American (Alone) : 0.921"),
    Tutor(name: "Massachusetts", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Adults Reporting to Have a Personal Doctor or Health Care Provider : 1",
          top2:"Percent population with health insurance : 1",
          top3:"Estimated median income of a family : 0.98",
          top4:"Percent of population with at least a bachelor's degree : 0.98",
          top5:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with depression : 0.98",
          top6:"Percent of Total Expenses Spent on Education : 0.96",
          top7:"Rate of fitness and recreational sports centers per 100,000 people : 0.96",
          top8:"Estimated median income of a household : 0.941",
          top9:"Amount Spent per Household on Alcohol : 0.921",
          top10:"Estimated average annual amount spent per household on food away from home : 0.901"),
    Tutor(name: "Michigan", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with heart failure : 0.98",
          top2:"Percent of non-federal jobs in Manufacturing in 2019 : 0.958",
          top3:"Percent of Adults Reporting to Have a Personal Doctor or Health Care Provider : 0.9",
          top4:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with coronary artery disease : 0.862",
          top5:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with chronic kidney disease : 0.862",
          top6:"Average Annual Dollars per Person Spent on Medical Care : 0.862",
          top7:"Percent population with health insurance : 0.843",
          top8:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with depression : 0.823",
          top9:"Percent of Adults Ever Diagnosed with Depression : 0.82",
          top10:"Rate of beer, wine, and liquor stores per 100,000 people in 2017. : 0.784"),
    Tutor(name: "Minnesota", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with depression : 0.96",
          top2:"Percent population with health insurance : 0.901",
          top3:"Estimated median income of a family : 0.803",
          top4:"Percent of population with at least a bachelor's degree : 0.803",
          top5:"Amount Spent per Household on Alcohol : 0.764",
          top6:"Percent Population Asian (Alone) : 0.764",
          top7:"Percent Population Asian (Alone) Non-Hispanic/Latino : 0.764",
          top8:"Percent Population White (Alone) Non-Hispanic/Latino : 0.764",
          top9:"Percent of non-federal jobs in Manufacturing in 2019 : 0.75",
          top10:"Estimated median income of a household : 0.745"),
    Tutor(name: "Mississippi", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Adults Reporting to be Overweight (BMI > 24.9) : 1",
          top2:"Percent of Total Expenses Spent on Housing : 0.98",
          top3:"Percent of Adults Reporting to be Obese (BMI of 30 or Greater) : 0.98",
          top4:"Percent change in the number of deaths from stroke : 0.98",
          top5:"Percent Families in Poverty : 0.98",
          top6:"Percent Population Black or African American (Alone) : 0.98",
          top7:"Percent Population Black or African American (Alone) Non-Hispanic/Latino : 0.98",
          top8:"Percent of Adults Ever Diagnosed with Diabetes : 0.96",
          top9:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with high blood pressure : 0.96",
          top10:"Rate of adult deaths from cancer per 100,000 people : 0.94"),
    Tutor(name: "Missouri", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with depression. : 0.901",
          top2:"Percent of Adults Reporting to be Obese (BMI of 30 or Greater) : 0.84",
          top3:"Rate of adult deaths from cancer per 100,000 people in 2020. : 0.8",
          top4:"Percent of Adults Ever Diagnosed with Depression : 0.76",
          top5:"Percent of non-federal jobs in Utilities in 2019 : 0.729",
          top6:"Percent Population White (Alone) Non-Hispanic/Latino : 0.725",
          top7:"Percent of Total Expenses Spent on Housing : 0.705",
          top8:"Percent Population White (Alone) : 0.686",
          top9:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with coronary artery disease : 0.666",
          top10:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with heart failure : 0.666"),
    Tutor(name: "Montana", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent change in the number of deaths from coronary heart disease : 0.98",
          top2:"Percent Population White (Alone) Non-Hispanic/Latino : 0.921",
          top3:"Percent of non-federal jobs in Construction in 2019 : 0.916",
          top4:"Percent Population White (Alone) : 0.901",
          top5:"Rate of fitness and recreational sports centers per 100,000 people : 0.882",
          top6:"Percent of Adults Reporting to be Overweight (BMI > 24.9 and < 30) : 0.88",
          top7:"Percent of non-federal jobs in Mining, Quarrying, and Oil and Gas Extraction in 2019 : 0.854",
          top8:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019 : 0.854",
          top9:"Average Annual Dollars per Person Spent on Medical Care : 0.784",
          top10:"Percent of non-federal jobs in Utilities in 2019 : 0.75"),
    Tutor(name: "Nebraska", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019 : 0.916",
          top2:"Rate of fitness and recreational sports centers per 100,000 people : 0.823",
          top3:"Percent of Adults Reporting to be Overweight (BMI > 24.9) : 0.8",
          top4:"Percent of non-federal jobs in Utilities in 2019 : 0.791",
          top5:"Percent Population White (Alone) : 0.745",
          top6:"Percent of non-federal jobs in Transportation and Warehousing in 2019 : 0.729",
          top7:"Percent Population White (Alone) Non-Hispanic/Latino : 0.705",
          top8:"Percent of Adults Reporting to be Obese (BMI of 30 or Greater) : 0.7",
          top9:"Percent of non-federal jobs in Manufacturing in 2019 : 0.687",
          top10:"Percent Population  Hispanic or Latino : 0.627"),
    Tutor(name: "Nevada", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent change in the number of deaths from stroke : 1",
          top2:"Percent change in the number of deaths from chronic lower respiratory disease : 1",
          top3:"Percent change in the number of deaths from coronary heart disease : 1",
          top4:"Percent of Adults Reporting to be Overweight (BMI > 24.9 and < 30) : 1",
          top5:"Rate of limited-service restaurants per 100,000 people in 2017. : 0.921",
          top6:"Percent Population Asian (Alone) : 0.901",
          top7:"Percent Population Asian (Alone) Non-Hispanic/Latino : 0.901",
          top8:"Percent Population  Hispanic or Latino : 0.901",
          top9:"Percent of non-federal jobs in Transportation and Warehousing in 2019 : 0.895",
          top10:"Percent of non-federal jobs in Mining, Quarrying, and Oil and Gas Extraction in 2019 : 0.833"),
    Tutor(name: "New Hampshire", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Average Annual Dollars per Person Spent on Medical Care : 0.98",
          top2:"Percent of Adults Reporting to Have a Personal Doctor or Health Care Provider : 0.98",
          top3:"Rate of fitness and recreational sports centers per 100,000 people : 0.98",
          top4:"Percent Population White (Alone) Non-Hispanic/Latino : 0.941",
          top5:"Percent Population White (Alone) : 0.941",
          top6:"Estimated median income of a family : 0.901",
          top7:"Amount Spent per Household on Alcohol : 0.882",
          top8:"Estimated median income of a household : 0.862",
          top9:"Percent of population with at least a bachelor's degree : 0.843",
          top10:"Estimated average annual amount spent per household on housing : 0.823"),
    Tutor(name: "New Jersey", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with coronary artery disease : 0.98",
          top2:"Estimated average annual amount spent per household on housing : 0.98",
          top3:"Amount Spent per Household on All Household Expenses : 0.98",
          top4:"Estimated average annual amount spent per household on food away from home : 0.98",
          top5:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with high cholesterol : 0.96",
          top6:"Percent Population Asian (Alone) : 0.96",
          top7:"Percent Population Asian (Alone) Non-Hispanic/Latino : 0.96",
          top8:"Estimated median income of a household : 0.96",
          top9:"Percent of Total Expenses Spent on Education : 0.96",
          top10:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with diabetes : 0.941"),
    Tutor(name: "New Mexico", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent Population  Hispanic or Latino : 0.98",
          top2:"Percent Families in Poverty : 0.941",
          top3:"Percent change in the number of deaths from coronary heart disease : 0.92",
          top4:"Percent of non-federal jobs in Mining, Quarrying, and Oil and Gas Extraction in 2019 : 0.916",
          top5:"Percent of Total Expenses Spent on Housing : 0.882",
          top6:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019 : 0.875",
          top7:"Percent of non-federal jobs in Utilities in 2019 : 0.812",
          top8:"Percent of non-federal jobs in Construction in 2019 : 0.791",
          top9:"Percent of Adults Ever Diagnosed with Diabetes : 0.72",
          top10:"Percent change in the number of deaths from chronic lower respiratory disease : 0.62"),
    Tutor(name: "New York", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Adults Reporting a Physical Checkup in the Past Year : 0.98",
          top2:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with diabetes : 0.96",
          top3:"Rate of limited-service restaurants per 100,000 people : 0.96",
          top4:"Percent Population Asian (Alone) : 0.941",
          top5:"Percent Population Asian (Alone) Non-Hispanic/Latino : 0.941",
          top6:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with coronary artery disease : 0.862",
          top7:"Percent of population with at least a bachelor's degree : 0.823",
          top8:"Percent population with health insurance : 0.823",
          top9:"Percent Population  Hispanic or Latino : 0.823",
          top10:"Rate of beer, wine, and liquor stores per 100,000 people in 2017. : 0.803"),
    Tutor(name: "North Carolina", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent Population Black or African American (Alone) : 0.843",
          top2:"Percent Population Black or African American (Alone) Non-Hispanic/Latino : 0.843",
          top3:"Percent of Adults Reporting a Physical Checkup in the Past Year : 0.8",
          top4:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with diabetes : 0.764",
          top5:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with chronic kidney disease : 0.745",
          top6:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with high blood pressure : 0.745",
          top7:"Percent of non-federal jobs in Manufacturing in 2019 : 0.729",
          top8:"Percent of Adults Ever Diagnosed with Diabetes : 0.72",
          top9:"Percent of Total Expenses Spent on Housing : 0.705",
          top10:"Percent Families in Poverty : 0.705"),
    Tutor(name: "North Dakota", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of non-federal jobs in Mining, Quarrying, and Oil and Gas Extraction in 2019 : 0.979",
          top2:"Percent of Adults Reporting to be Overweight (BMI > 24.9) : 0.96",
          top3:"Percent of non-federal jobs in Construction in 2019 : 0.895",
          top4:"Percent Population White (Alone) Non-Hispanic/Latino : 0.882",
          top5:"Percent of non-federal jobs in Utilities in 2019 : 0.875",
          top6:"Percent Population White (Alone) : 0.862",
          top7:"Percent of Adults Reporting to be Obese (BMI of 30 or Greater) : 0.86",
          top8:"Percent of Adults Reporting to be Overweight (BMI > 24.9 and < 30) : 0.78",
          top9:"Percent of non-federal jobs in Transportation and Warehousing in 2019 : 0.77",
          top10:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019 : 0.75"),
    Tutor(name: "Ohio", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Rate of limited-service restaurants per 100,000 people : 0.862",
          top2:"Rate of adult deaths from cancer per 100,000 people in 2020. : 0.86",
          top3:"Percent of non-federal jobs in Manufacturing in 2019 : 0.854",
          top4:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with depression : 0.803",
          top5:"Percent Population White (Alone) Non-Hispanic/Latino : 0.745",
          top6:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with heart failure : 0.745",
          top7:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with chronic kidney disease : 0.745",
          top8:"Percent of Adults Reporting to be Overweight (BMI > 24.9) : 0.74",
          top9:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with high cholesterol : 0.725",
          top10:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with coronary artery disease : 0.705"),
    Tutor(name: "Oklahoma", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with heart failure : 0.98",
          top2:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with coronary artery disease : 0.941",
          top3:"Percent of non-federal jobs in Mining, Quarrying, and Oil and Gas Extraction in 2019 : 0.937",
          top4:"Rate of adult deaths from cancer per 100,000 people : 0.92",
          top5:"Percent of non-federal jobs in Utilities in 2019 : 0.916",
          top6:"Percent of Adults Reporting to be Overweight (BMI > 24.9) : 0.88",
          top7:"Percent of Adults Ever Diagnosed with Depression : 0.86",
          top8:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with depression : 0.843",
          top9:"Percent Families in Poverty : 0.823",
          top10:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with chronic kidney disease : 0.803"),
    Tutor(name: "Oregon", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Adults Ever Diagnosed with Depression : 0.98",
          top2:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019 : 0.958",
          top3:"Percent Population  Hispanic or Latino : 0.725",
          top4:"Percent Population Asian (Alone) Non-Hispanic/Latino : 0.705",
          top5:"Percent Population Asian (Alone) : 0.705",
          top6:"Percent of population with at least a bachelor's degree : 0.686",
          top7:"Percent of non-federal jobs in Construction in 2019 : 0.666",
          top8:"Percent of non-federal jobs in Manufacturing in 2019 : 0.666",
          top9:"Estimated median income of a household : 0.647",
          top10:"Percent population with health insurance : 0.627"),
    Tutor(name: "Pennsylvania", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Average Annual Dollars per Person Spent on Medical Care : 0.901",
          top2:"Percent of non-federal jobs in Transportation and Warehousing in 2019 : 0.875",
          top3:"Percent of Adults Reporting to Have a Personal Doctor or Health Care Provider : 0.86",
          top4:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with high cholesterol : 0.843",
          top5:"Rate of adult deaths from cancer per 100,000 people : 0.84",
          top6:"Percent population with health insurance : 0.784",
          top7:"Percent of non-federal jobs in Mining, Quarrying, and Oil and Gas Extraction in 2019 : 0.729",
          top8:"Rate of beer, wine, and liquor stores per 100,000 people : 0.725",
          top9:"Percent of Adults Ever Diagnosed with Depression : 0.7",
          top10:"Percent of Adults Reporting a Physical Checkup in the Past Year : 0.7"),
    Tutor(name: "Rhode Island", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Adults Reporting a Physical Checkup in the Past Year : 1",
          top2:"Percent of Adults Reporting to Have a Personal Doctor or Health Care Provider : 0.96",
          top3:"Percent of Adults Reporting to be Overweight (BMI > 24.9 and < 30) : 0.94",
          top4:"Rate of beer, wine, and liquor stores per 100,000 people : 0.921",
          top5:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with depression : 0.921",
          top6:"Percent population with health insurance : 0.921",
          top7:"Rate of fitness and recreational sports centers per 100,000 people : 0.862",
          top8:"Rate of limited-service restaurants per 100,000 people : 0.823",
          top9:"Percent Population  Hispanic or Latino : 0.764",
          top10:"Estimated median income of a family : 0.745"),
    Tutor(name: "South Carolina", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent change in the number of deaths from chronic lower respiratory disease : 0.94",
          top2:"Percent of Adults Reporting to be Overweight (BMI > 24.9) : 0.9",
          top3:"Percent Population Black or African American (Alone) Non-Hispanic/Latino : 0.882",
          top4:"Percent Population Black or African American (Alone) : 0.882",
          top5:"Percent of non-federal jobs in Utilities in 2019 : 0.875",
          top6:"Percent of Adults Ever Diagnosed with Diabetes : 0.86",
          top7:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with high cholesterol : 0.843",
          top8:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with high blood pressure : 0.823",
          top9:"Percent change in the number of deaths from stroke : 0.82",
          top10:"Percent of non-federal jobs in Manufacturing in 2019 : 0.791"),
    Tutor(name: "South Dakota", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Adults Reporting to be Overweight (BMI > 24.9 and < 30) : 0.98",
          top2:"Percent Population White (Alone) Non-Hispanic/Latino : 0.823",
          top3:"Percent Population White (Alone) : 0.803",
          top4:"Rate of fitness and recreational sports centers per 100,000 people : 0.745",
          top5:"Percent of Adults Reporting to be Overweight (BMI > 24.9) : 0.64",
          top6:"Rate of adult deaths from cancer per 100,000 people : 0.64",
          top7:"Percent of Total Expenses Spent on Housing : 0.607",
          top8:"Percent Families in Poverty : 0.49",
          top9:"Estimated median income of a family : 0.47",
          top10:"Rate of beer, wine, and liquor stores per 100,000 people : 0.47"),
    Tutor(name: "Tennessee", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of non-federal jobs in Transportation and Warehousing in 2019 : 0.979",
          top2:"Percent of Adults Ever Diagnosed with Depression : 0.96",
          top3:"Percent of Adults Ever Diagnosed with Diabetes : 0.9",
          top4:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with chronic kidney disease : 0.882",
          top5:"Percent change in the number of deaths from chronic lower respiratory disease : 0.88",
          top6:"Rate of adult deaths from cancer per 100,000 people in 2020. : 0.82",
          top7:"Percent of non-federal jobs in Manufacturing in 2019 : 0.812",
          top8:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with high blood pressure : 0.803",
          top9:"Percent Population Black or African American (Alone) Non-Hispanic/Latino : 0.803",
          top10:"Percent Population Black or African American (Alone) : 0.803"),
    Tutor(name: "Texas", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with chronic kidney disease : 0.941",
          top2:"Percent Population  Hispanic or Latino : 0.941",
          top3:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with heart failure : 0.901",
          top4:"Percent of non-federal jobs in Mining, Quarrying, and Oil and Gas Extraction in 2019 : 0.895",
          top5:"Percent change in the number of deaths from coronary heart disease : 0.86",
          top6:"Percent of Adults Reporting to be Overweight (BMI > 24.9) : 0.84",
          top7:"Percent change in the number of deaths from stroke : 0.84",
          top8:"Percent of non-federal jobs in Construction in 2019 : 0.812",
          top9:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with coronary artery disease : 0.803",
          top10:"Percent of Medicare fee-for-service beneficiaries who are diagnosed with high cholesterol : 0.803"),
    Tutor(name: "Utah", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent change in the number of deaths from chronic lower respiratory disease : 0.98",
          top2:"Percent of non-federal jobs in Construction in 2019 : 0.958",
          top3:"Percent of Adults Ever Diagnosed with Depression : 0.94",
          top4:"Percent change in the number of deaths from coronary heart disease : 0.9",
          top5:"Percent change in the number of deaths from stroke : 0.9",
          top6:"Percent of non-federal jobs in Mining, Quarrying, and Oil and Gas Extraction in 2019 : 0.791",
          top7:"Estimated average annual amount spent per household on food away from home : 0.784",
          top8:"Percent Population White (Alone) : 0.764",
          top9:"Estimated median income of a household : 0.764",
          top10:"Estimated average annual amount spent per household on housing : 0.745"),
    Tutor(name: "Vermont", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent Population White (Alone) : 0.98",
          top2:"Percent Population White (Alone) Non-Hispanic/Latino : 0.96",
          top3:"Percent population with health insurance : 0.941",
          top4:"Percent of Adults Reporting to Have a Personal Doctor or Health Care Provider : 0.94",
          top5:"Percent change in the number of deaths from coronary heart disease : 0.94",
          top6:"Average Annual Dollars per Person Spent on Medical Care : 0.901",
          top7:"Percent of population with at least a bachelor's degree : 0.901",
          top8:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019 : 0.833",
          top9:"Rate of beer, wine, and liquor stores per 100,000 people : 0.823",
          top10:"Rate of fitness and recreational sports centers per 100,000 people : 0.784"),
    Tutor(name: "Virginia", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of Total Expenses Spent on Education : 0.862",
          top2:"Percent of population with at least a bachelor's degree : 0.862",
          top3:"Percent Population Asian (Alone) Non-Hispanic/Latino : 0.862",
          top4:"Percent Population Asian (Alone) : 0.862",
          top5:"Estimated median income of a family : 0.843",
          top6:"Amount Spent per Household on Alcohol : 0.843",
          top7:"Estimated average annual amount spent per household on housing : 0.843",
          top8:"Amount Spent per Household on All Household Expenses : 0.843",
          top9:"Estimated average annual amount spent per household on food away from home : 0.843",
          top10:"Estimated median income of a household : 0.823"),
    Tutor(name: "Washington", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019 : 0.979",
          top2:"Percent Population Asian (Alone) Non-Hispanic/Latino : 0.921",
          top3:"Percent Population Asian (Alone) : 0.921",
          top4:"Percent of Adults Ever Diagnosed with Depression : 0.88",
          top5:"Estimated median income of a household : 0.843",
          top6:"Estimated median income of a family : 0.823",
          top7:"Amount Spent per Household on Alcohol : 0.823",
          top8:"Estimated average annual amount spent per household on housing : 0.803",
          top9:"Amount Spent per Household on All Household Expenses : 0.803",
          top10:"Estimated average annual amount spent per household on food away from home : 0.803"),
    Tutor(name: "West Virgina", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of non-federal jobs in Utilities in 2019 : 1",
          top2:"Percent of Adults Ever Diagnosed with Depression : 1",
          top3:"Rate of adult deaths from cancer per 100,000 people in 2020. : 1",
          top4:"Percent of Adults Ever Diagnosed with Diabetes : 1",
          top5:"Percent of Adults Reporting to be Overweight (BMI > 24.9) : 0.98",
          top6:"Percent Population White (Alone) Non-Hispanic/Latino : 0.98",
          top7:"Percent of Adults Reporting to be Obese (BMI of 30 or Greater) : 0.98",
          top8:"Percent Population White (Alone) : 0.96",
          top9:"Percent of Adults Reporting a Physical Checkup in the Past Year : 0.96",
          top10:"Percent of non-federal jobs in Mining, Quarrying, and Oil and Gas Extraction in 2019 : 0.958"),
    Tutor(name: "Wisconsin", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of non-federal jobs in Manufacturing in 2019 : 0.979",
          top2:"Percent of Adults Reporting to be Overweight (BMI > 24.9 and < 30) : 0.86",
          top3:"Percent population with health insurance : 0.803",
          top4:"Percent of Adults Reporting to Have a Personal Doctor or Health Care Provider : 0.8",
          top5:"Percent Population White (Alone) Non-Hispanic/Latino : 0.784",
          top6:"Percent Population White (Alone) : 0.784",
          top7:"Average Annual Dollars per Person Spent on Medical Care : 0.784",
          top8:"Percent of Adults Reporting to be Overweight (BMI > 24.9) : 0.72",
          top9:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019 : 0.687",
          top10:"Rate of fitness and recreational sports centers per 100,000 people : 0.666"),
    Tutor(name: "Wyoming", headline: "Top 10 SDoH Percentile Ranking",
          top1:"Percent of non-federal jobs in Mining, Quarrying, and Oil and Gas Extraction in 2019 : 1",
          top2:"Percent of non-federal jobs in Construction in 2019 : 0.979",
          top3:"Percent of non-federal jobs in Utilities in 2019 : 0.937",
          top4:"Percent Population White (Alone) : 0.921",
          top5:"Percent Population White (Alone) Non-Hispanic/Latino : 0.862",
          top6:"Percent of non-federal jobs in Agriculture, Forestry, Fishing and Hunting in 2019 : 0.812",
          top7:"Rate of fitness and recreational sports centers per 100,000 people : 0.803",
          top8:"Percent change in the number of deaths from coronary heart disease : 0.8",
          top9:"Percent change in the number of deaths from chronic lower respiratory disease : 0.8",
          top10:"Rate of beer, wine, and liquor stores per 100,000 people : 0.764"),
]
#endif

